server:
  port: 8080

spring:

  application:
    name: notification-service

  datasource:
    url: jdbc:postgresql://localhost:5432/notification_db
    username: postgres
    password: Ritesh1408

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#  kafka:
#    bootstrap-servers: localhost:9092
#    consumer:
#      group-id: notification-group
#      auto-offset-reset: earliest
#
  data:
    redis:
      host: localhost
      port: 6379
#
jwt:
  secret: mysupersecretkeymysupersecretkey123
  expiration: 3600000